const transportationMatrixData = [
    {
        sourceCode: 1005,
        source: "Chikballapur",
        destinationCode: 1000,
        destination: "Bangalore1",
        transportationCost: 1.08,
    },
    {
        sourceCode: 1005,
        source: "Chikballapur",
        destinationCode: 1028,
        destination: "Bangalore2",
        transportationCost: 1.08,
    },
    {
        sourceCode: 1005,
        source: "Chikballapur",
        destinationCode: 1017,
        destination: "Bangalore2",
        transportationCost: 2.29,
    },
    {
        sourceCode: 1005,
        source: "Chikballapur",
        destinationCode: 1020,
        destination: "Hyderabad",
        transportationCost: 5.82,
    },
    {
        sourceCode: 1005,
        source: "Chikballapur",
        destinationCode: 1031,
        destination: "Vijayawada",
        transportationCost: 3.64,
    },
    {
        sourceCode: 1007,
        source: "Malur",
        destinationCode: 1009,
        destination: "Chennai",
        transportationCost: 1.65,
    },
    {
        sourceCode: 1007,
        source: "Malur",
        destinationCode: 1000,
        destination: "Bangalore1",
        transportationCost: 0.53,
    },
    {
        sourceCode: 1007,
        source: "Malur",
        destinationCode: 1017,
        destination: "Coimbatore",
        transportationCost: 2.29,
    },
    {
        sourceCode: 1007,
        source: "Malur",
        destinationCode: 1020,
        destination: "Hyderabad",
        transportationCost: 5.82,
    },
    {
        sourceCode: 1007,
        source: "Malur",
        destinationCode: 1031,
        destination: "Vijayawada",
        transportationCost: 3.64,
    },
    {
        sourceCode: 1007,
        source: "Malur",
        destinationCode: 1028,
        destination: "Bangalore2",
        transportationCost: 0.53,
    },
    {
        sourceCode: 1006,
        source: "Hosur",
        destinationCode: 1009,
        destination: "Chennai",
        transportationCost: 1.5,
    },
    {
        sourceCode: 1006,
        source: "Hosur",
        destinationCode: 1000,
        destination: "Bangalore1",
        transportationCost: 0.97,
    },
    {
        sourceCode: 1006,
        source: "Hosur",
        destinationCode: 1017,
        destination: "Coimbatore",
        transportationCost: 2.29,
    },
    {
        sourceCode: 1006,
        source: "Hosur",
        destinationCode: 1028,
        destination: "Bangalore2",
        transportationCost: 0.97,
    },
    {
        sourceCode: 1039,
        source: "Ooty",
        destinationCode: 1017,
        destination: "Coimbatore",
        transportationCost: 1.65,
    },
    {
        sourceCode: 1010,
        source: "Thindivanam",
        destinationCode: 1009,
        destination: "Chennai",
        transportationCost: 1.9,
    },


]
export default transportationMatrixData;