// ACTION TYPES
export const GET_NFNVITEM = 'GET_NFNVITEM';
export const GET_NFNVCATEGORY = 'GET_NFNVCATEGORY';
export const NFNVCATEGORY_ERROR = 'NFNVCATEGORY_ERROR';
export const ADD_NFNVITEM = 'ADD_NFNVITEM';
export const UPDATE_NFNVITEM = 'UPDATE_NFNVITEM';
export const DELETE_NFNVITEM = 'DELETE_NFNVITEM';
export const NFNVITEM_ERROR = 'NFNVITEM_ERROR';
