// ACTION TYPES
export const GET_LOCATION = 'GET_LOCATION';
export const ADD_LOCATION = 'ADD_LOCATION';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const LOCATION_ERROR = 'LOCATION_ERROR';
