// ACTION TYPES
export const GET_LOCATIONMAT = 'GET_LOCATIONMAT';
export const ADD_LOCATIONMAT = 'ADD_LOCATIONMAT';
export const UPDATE_LOCATIONMAT = 'UPDATE_LOCATIONMAT';
export const DELETE_LOCATIONMAT = 'DELETE_LOCATIONMAT';
export const LOCATIONMAT_ERROR = 'LOCATIONMAT_ERROR';
