// ACTION TYPES
export const GET_MARKETCOMMISSION = 'GET_MARKETCOMMISSION';
export const MARKETCOMMISSION_ERROR_TRACKER = 'MARKETCOMMISSION_ERROR_TRACKER';
export const UPDATE_MARKETCOMMISSION =  'UPDATE_MARKETCOMMISSION'