// ACTION TYPES
export const GET_CONVERSION = 'GET_CONVERSION';
export const ADD_CONVERSION = 'ADD_CONVERSION';
export const UPDATE_CONVERSION = 'UPDATE_CONVERSION';
export const DELETE_CONVERSION = 'DELETE_CONVERSION';
export const CONVERSION_ERROR = 'CONVERSION_ERROR';
