// ACTION TYPES
export const GET_MARKETWISE = 'GET_MARKETWISE';
export const ADD_MARKETWISE = 'ADD_MARKETWISE';
export const UPDATE_MARKETWISE = 'UPDATE_MARKETWISE';
export const DELETE_MARKETWISE = 'DELETE_MARKETWISE';
export const MARKETWISE_ERROR = 'MARKETWISE_ERROR';
