// ACTION TYPES
export const ADD_BMMANAGEMENT = 'ADD_BMMANAGEMENT';
export const UPDATE_BMMANAGEMENT = 'UPDATE_BMMANAGEMENT';
export const DELETE_BMMANAGEMENT = 'DELETE_BMMANAGEMENT';
export const GET_BMMANAGEMENT = 'GET_BMMANAGEMENT';
export const BMMANAGEMENT_ERROR = 'BMMANAGEMENT_ERROR'


