// ACTION TYPES
export const GET_LOCATIONMATRIX = 'GET_LOCATIONMATRIX';
export const ADD_LOCATIONMATRIX = 'ADD_LOCATIONMATRIX';
export const UPDATE_LOCATIONMATRIX = 'UPDATE_LOCATIONMATRIX';
export const DELETE_LOCATIONMATRIX = 'DELETE_LOCATIONMATRIX';
export const LOCATIONMATRIX_ERROR = 'LOCATIONMATRIX_ERROR';
