// ACTION TYPES
export const GET_IMPORTED = 'GET_IMPORTED';
export const ADD_IMPORTED = 'ADD_IMPORTED';
export const UPDATE_IMPORTED = 'UPDATE_IMPORTED';
export const DELETE_IMPORTED = 'DELETE_IMPORTED';
export const IMPORTED_ERROR = 'IMPORTED_ERROR';
