// ACTION TYPES
export const GET_TRANSPORTATION = "GET_TRANSPORTATION";
export const ADD_TRANSPORTATION = "ADD_TRANSPORTATION";
export const UPDATE_TRANSPORTATION = "UPDATE_TRANSPORTATION";
export const DELETE_TRANSPORTATION = "DELETE_TRANSPORTATION";
export const TRANSPORTATION_ERROR = "TRANSPORTATION_ERROR";
